print("Welcome to our Mad Lib Game")

print("Please fill out following options")
print()
color = input("Enter a color: ")
color_2 = input("Enter second color: ")
adjective = input("Enter a adjective: ")
noun = input("Enter a  noun: ")
name=input("Enter a name")
print("<---------------------------------------------------->")
print("Roses are", color)
print(color_2 + " are blue")
print("we love" , adjective, noun)
print("hope ",name ,"love them too")
print("<---------------------------------------------------->")